// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: protos/globe_sort.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Len           uint32                 `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_protos_globe_sort_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_protos_globe_sort_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_protos_globe_sort_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetLen() uint32 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *Record) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Final         bool                   `protobuf:"varint,2,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_protos_globe_sort_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_globe_sort_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_protos_globe_sort_proto_rawDescGZIP(), []int{1}
}

func (x *DataRequest) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *DataRequest) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=Ack,proto3" json:"Ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_protos_globe_sort_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_globe_sort_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_protos_globe_sort_proto_rawDescGZIP(), []int{2}
}

func (x *DataResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_protos_globe_sort_proto protoreflect.FileDescriptor

const file_protos_globe_sort_proto_rawDesc = "" +
	"\n" +
	"\x17protos/globe_sort.proto\x12\tglobesort\"B\n" +
	"\x06Record\x12\x10\n" +
	"\x03len\x18\x01 \x01(\rR\x03len\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"P\n" +
	"\vDataRequest\x12+\n" +
	"\arecords\x18\x01 \x03(\v2\x11.globesort.RecordR\arecords\x12\x14\n" +
	"\x05final\x18\x02 \x01(\bR\x05final\" \n" +
	"\fDataResponse\x12\x10\n" +
	"\x03Ack\x18\x01 \x01(\bR\x03Ack2J\n" +
	"\vNodeService\x12;\n" +
	"\bSendData\x12\x16.globesort.DataRequest\x1a\x17.globesort.DataResponseB\x18Z\x16globesort/protos/pb;pbb\x06proto3"

var (
	file_protos_globe_sort_proto_rawDescOnce sync.Once
	file_protos_globe_sort_proto_rawDescData []byte
)

func file_protos_globe_sort_proto_rawDescGZIP() []byte {
	file_protos_globe_sort_proto_rawDescOnce.Do(func() {
		file_protos_globe_sort_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_globe_sort_proto_rawDesc), len(file_protos_globe_sort_proto_rawDesc)))
	})
	return file_protos_globe_sort_proto_rawDescData
}

var file_protos_globe_sort_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_globe_sort_proto_goTypes = []any{
	(*Record)(nil),       // 0: globesort.Record
	(*DataRequest)(nil),  // 1: globesort.DataRequest
	(*DataResponse)(nil), // 2: globesort.DataResponse
}
var file_protos_globe_sort_proto_depIdxs = []int32{
	0, // 0: globesort.DataRequest.records:type_name -> globesort.Record
	1, // 1: globesort.NodeService.SendData:input_type -> globesort.DataRequest
	2, // 2: globesort.NodeService.SendData:output_type -> globesort.DataResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_globe_sort_proto_init() }
func file_protos_globe_sort_proto_init() {
	if File_protos_globe_sort_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_globe_sort_proto_rawDesc), len(file_protos_globe_sort_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_globe_sort_proto_goTypes,
		DependencyIndexes: file_protos_globe_sort_proto_depIdxs,
		MessageInfos:      file_protos_globe_sort_proto_msgTypes,
	}.Build()
	File_protos_globe_sort_proto = out.File
	file_protos_globe_sort_proto_goTypes = nil
	file_protos_globe_sort_proto_depIdxs = nil
}
